name: Continuous Integration
# once the tests can run without a tupelo net spun up, turn this back on
# on: [push]
on: []

jobs:
  test:
    name: "run test suite"
    runs-on: ubuntu-latest
    env:
      GOPATH: /home/runner/work/dgit/go
      GOBIN: /home/runner/work/dgit/go/bin
    steps:
      - name: install go
        uses: actions/setup-go@v1
        with:
          go-version: 1.14
      - name: install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y make
      - uses: actions/checkout@v2
      - name: run tests
        run: make test
