name: Homebrew Bottle
# eventually this should run on release only
#on: [release]
# but every push is useful for testing
on: [push, release]

jobs:
  bottle:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, macos-10.15]
    steps:
      - name: install homebrew
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
